<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
        <GenerateProgramFile>false</GenerateProgramFile>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <TUnitImplicitUsings>true</TUnitImplicitUsings>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <PreserveCompilationContext>true</PreserveCompilationContext>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ManagedCode.TimeSeries" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Microsoft.Orleans.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Orleans.Serialization" />
        <PackageReference Include="Microsoft.Orleans.TestingHost" />
        <PackageReference Include="System.Linq.Async" />
        <PackageReference Include="System.Threading.RateLimiting" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
        <PackageReference Include="Microsoft.AspNetCore.TestHost" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Orleans.Sdk" />
        <PackageReference Include="Microsoft.Orleans.Serialization.SystemTextJson" />
        <PackageReference Include="Microsoft.Orleans.Serialization.TestKit" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="TUnit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ManagedCode.Orleans.RateLimiting.Client\ManagedCode.Orleans.RateLimiting.Client.csproj" />
        <ProjectReference Include="..\ManagedCode.Orleans.RateLimiting.Core\ManagedCode.Orleans.RateLimiting.Core.csproj" />
        <ProjectReference Include="..\ManagedCode.Orleans.RateLimiting.Server\ManagedCode.Orleans.RateLimiting.Server.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Shouldly" />
        <Using Include="TUnit.Core" />
    </ItemGroup>

</Project>
