<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>12</LangVersion>
        <OutputType>Library</OutputType>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <!--NuGet-->
    <PropertyGroup>
        <Title>ManagedCode.Orleans.RateLimiting.Client</Title>
        <PackageId>ManagedCode.Orleans.RateLimiting.Client</PackageId>
        <Description>RateLimiting base on Orleans</Description>
        <PackageTags>managedcode, orleans, RateLimiting</PackageTags>
    </PropertyGroup>

    <ItemGroup>

        <PackageReference Include="ManagedCode.Communication" Version="9.6.5" />

        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
        <PackageReference Include="Microsoft.Orleans.Client" Version="9.2.1" />
        <PackageReference Include="System.Threading.RateLimiting" Version="9.0.10" />

    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ManagedCode.Orleans.RateLimiting.Core\ManagedCode.Orleans.RateLimiting.Core.csproj" />
    </ItemGroup>

</Project>
